### ISSUE TITLE
Completion of the First 7 Episodes of the Education Series

### ISSUE THREAD

**Issue by mucahitgoncu** [octoposprime/op-game#1]
The link to the first education series; https://youtube.com/playlist?list=PLbgnCnWZjdwbFZ0ypbyY5ZUfEtyUKUsZQ&si=k4Fy8ii_unGDINAO

**Comment by Sddilora** [comment]
Is this made intentionally or is this a mistake? Should we complete this series?

**Comment by husamettinarabaci** [comment]
This issue is transferred in the op-game.
@mucahitgoncu 
Please add assignees and the correct labels.
Please use the correct status and iteration.
@Sddilora 
Can you give information about "how does OctopOSPrime Project works" to @mucahitgoncu ?

**Comment by mucahitgoncu** [comment]
.
