### ISSUE TITLE
Flappy Bird Game Improvements

### ISSUE THREAD

**Issue by mucahitgoncu** [octoposprime/op-game#19]
#### Bug Fixes:
- Fix distance errors in pipe spacing.
- Ensure ground flow speed matches the pipes' speed.

#### Features:
- Implement three interfaces:
  - Start menu
  - Pause menu
  - Game over menu
- Increase game speed by 8% every 8 points scored.
- Add a best score feature.
- Turn the score and best score red when they are equal.

**Comment by Weal1041** [comment]
done sir
































(Ez
