### ISSUE TITLE
Completion the first 5 episodes of the second educational series.

### ISSUE THREAD

**Issue by mucahitgoncu** [octoposprime/op-game#5]
The link to the first education series: https://youtube.com/playlist?list=PLgOEwFbvGm5o8hayFB6skAfa8Z-mw4dPV&si=mBXrAlYBDp28Xizj

**Comment by osmangozukucuk** [comment]
![Image](https://github.com/octoposprime/op-game/assets/136318716/6674878e-20b0-45ce-b11a-c1db896e1b17)
