### ISSUE TITLE
Sync Labels

### ISSUE THREAD

**Issue by husamettinarabaci** [octoposprime/op-game#6]
Please sync all labels from 
https://github.com/orgs/octoposprime/discussions/14

Names and Colors

**Comment by mucahitgoncu** [comment]
Gameplay (Changes related to game mechanics): (#ff7f50)
Graphics (Changes or improvements related to graphics): (#1e90ff)
Sound (Changes or fixes related to sound): (#ff69b4)
Educational (Tutorial content ): (#4CAF50)
UI/UX (Changes related to user interface or user experience): (#ffd700)
Networking (Issues or improvements related to networking): (#32cd32)
Performance (Issues or improvements related to performance): (#ff4500)
Localization (Changes or additions related to localization): (#ffa500)
Platform-specific (Platform-specific issues or improvements): (#808080)
Balance (Changes or fixes related to game balance): (#ff6347)
Bug (Issue reporting a bug): (#d73a4a)
Enhancement (Improvement or addition to an existing feature): (#a2eeef)
Refactor (Improving codebase structure, organization, or performance without altering external behavior): (#BBA612)
Documentation (Adding or improving documentation): (#0075ca)
Question (Asking a question): (#d876e3)
Duplicate (A copy of an existing issue): (#cfd3d7)
Invalid (An issue deemed invalid): (#e4e669)
Won't fix (An issue that won't be fixed or changed): (#ffffff)
Help wanted (An issue that requires community assistance): (#129e88)

**Comment by husamettinarabaci** [comment]
Please add your label advertisement in https://github.com/orgs/octoposprime/discussions/14 and wait until finish discussion. After you have to add all labels to this project.

**Comment by husamettinarabaci** [comment]
You have to sync all names, colors, and descriptions.

https://github.com/orgs/octoposprime/discussions/14#discussioncomment-9026048
